version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    branches:
      - main
      - dev
      - AkhilaPodilapu5-patch-2
      - AkhilaPodilapu5-patch-1
